services:

  mongos3:
    container_name: mongos3
    image: mongo:latest
    command: mongos --configdb config_rs/host.docker.internal:10001,host.docker.internal:10001,host.docker.internal:10003 --port 27017 --bind_ip_all
    ports:
      - 30002:27017
    networks:
      - mongo-demo-network

networks:
  mongo-demo-network:
    name: mongo-demo-network
    external: true
