
version: '3'

services:

  replicasvr1_1:
    container_name: replicasvr1_1
    image: mongo:latest
    command: mongod --replSet replica1_rs --dbpath /data/db --port 27017
    ports:
      - 20010:27017
    volumes:
      - replicasvr1_1:/data/db

  replicasvr1_2:
    container_name: replicasvr1_2
    image: mongo:latest
    command: mongod --replSet replica1_rs --dbpath /data/db --port 27017
    ports:
      - 20011:27017
    volumes:
      - replicasvr1_2:/data/db

  replicasvr1_3:
    container_name: replicasvr1_3
    image: mongo:latest
    command: mongod --replSet replica1_rs --dbpath /data/db --port 27017
    ports:
      - 20012:27017
    volumes:
      - replicasvr1_3:/data/db

volumes:
  replicasvr1_1:
  replicasvr1_2:
  replicasvr1_3:

