services:

  mongos2:
    container_name: mongos2
    image: mongo:latest
    command: mongos --configdb config_rs/configsvr1:27017,configsvr2:27017,configsvr3:27017 --port 27017 --bind_ip_all
    ports:
      - 30001:27017
    networks:
      - mongo-demo-network

networks:
  mongo-demo-network:
    name: mongo-demo-network
    external: true
